name: nix

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NIXPKGS_ALLOW_UNFREE: '1'

jobs:
  build:
    strategy:
      matrix:
        attr:
          - packages.x86_64-linux.installer-iso
          - packages.x86_64-linux.kernel
          - nixosConfigurations.default
          # - nixosConfigurations.default.config.system.build.toplevel
          - nixosConfigurations.thinker
          # - nixosConfigurations.thinker.config.system.build.toplevel
          - homeConfigurations.luis

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: nixbuild/nix-quick-install-action@v26
      with:
        nix_conf: |
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
          keep-outputs = true

    - name: Restore and cache Nix store
      uses: nix-community/cache-nix-action@v5
      with:
        key: nixcache-${{ hashFiles('**/*.nix') }}
        restore-keys: |
          nixcache-

        gc-linux: true
        gc-max-store-size-linux: 1000000000

        purge-caches: true
        purge-key: nixcache-
        purge-created: true
        purge-created-max-age: 42

    - uses: cachix/install-nix-action@V27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build --attr ${{ matrix.attr }}
